server.port: 9100
spring:
  application.name: authms
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/auth_db
    username:
    password:
    initialization-mode: always
  sql.init.mode: always